Signal implementaiton
JakubWronka/best-project-ever pull request #12
Opened 2022-06-02 17:42 UTC by PythonMaciej

* Fix requirements, create new data, first attempt on custom templates

* Add custom view templates for article

Co-authored-by: Jakub Wronka <jakubwronka7@gmail.com>

2022-06-02 17:48 UTC, JakubWronka requested changes
To discuss tomorrow, changes for signals are not visible

2022-06-03 09:19 UTC, JakubWronka approved these changes
Good job overall

2022-06-03 09:19 UTC, JakubWronka commented on bestprojectever/blog/signals.py
> +        content='Next user {user} is added'.format(user=user_number))
Add newline at the end of the file

2022-06-03 09:21 UTC, PythonMaciej commented on bestprojectever/blog/signals.py
> +        content='Next user {user} is added'.format(user=user_number))
done, thank you

2022-06-03 09:21 UTC, merged