GraphQL and Swagger implementation
JakubWronka/best-project-ever pull request #16
Opened 2022-09-20 08:33 UTC by PythonMaciej

No comment

2022-09-21 05:08 UTC, JakubWronka requested changes
Overall very good job, only some minor things to be addressed

2022-09-21 05:08 UTC, JakubWronka commented on bestprojectever/Dockerfile
> +RUN pip install "graphene-django>=2.0"
Can this be added in the requirements.txt file?

2022-09-21 05:08 UTC, JakubWronka commented on bestprojectever/blog/schema.py
> +from concurrent.futures.process import BrokenProcessPool
Is this import necessary? Because I see that it is not used here. If not necessary, please remove that line

2022-09-21 06:31 UTC, PythonMaciej commented on bestprojectever/Dockerfile
> +RUN pip install "graphene-django>=2.0"
I will try again to do it if possible else leave here with # comment.

2022-09-21 06:33 UTC, PythonMaciej commented on bestprojectever/blog/schema.py
> +from concurrent.futures.process import BrokenProcessPool
good point, thank you, will do that

2022-10-18 14:53 UTC, PythonMaciej commented on bestprojectever/Dockerfile
> +RUN pip install "graphene-django>=2.0"
corrected in the next commit

2022-10-18 14:54 UTC, PythonMaciej commented on bestprojectever/blog/schema.py
> +from concurrent.futures.process import BrokenProcessPool
corrected in the next commit

2022-10-18 15:04 UTC, PythonMaciej commented
Additionally I have addes swagger implementation to this PR

2022-10-23 16:29 UTC, JakubWronka requested changes
Looking good, some minor changes suggested, let me know what do you think about them

2022-10-23 16:29 UTC, JakubWronka commented on bestprojectever/bestprojectever/settings.py
> +EMAIL_HOST_PASSWORD = 'blablabla'   # password shared by another communication channel
Nit: maybe change it to "dummy_password" or  "mock_password" instead of "blablabla"?

2022-10-23 16:29 UTC, JakubWronka commented on bestprojectever/bestprojectever/urls.py
>  ]
Nit: Add a newline at the end of the file

2022-10-23 16:31 UTC, JakubWronka commented
Please also alter the PR name, so it reflects the changes that will be added (add info about swagger)

2022-10-25 14:15 UTC, PythonMaciej commented on bestprojectever/bestprojectever/settings.py
> +EMAIL_HOST_PASSWORD = 'blablabla'   # password shared by another communication channel
good point, corrected in the next commit

2022-10-25 14:16 UTC, PythonMaciej commented on bestprojectever/bestprojectever/urls.py
>  ]
good point, corrected in the next commit

2022-10-25 14:22 UTC, PythonMaciej commented
all comments are addressed, plase make re-review

2022-10-26 06:49 UTC, JakubWronka approved these changes

2022-10-26 06:51 UTC, merged